project_id = "kamogbeiycovoiiqfvvx"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[functions.generate-image]
verify_jwt = false

[functions.generate-voiceover]
verify_jwt = false

[functions.generate-script]
verify_jwt = false

[functions.stitch-video]
verify_jwt = false
